using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace PCRE.Analyzers;

internal static class GeneratorHelpers
{
    public static readonly SymbolDisplayFormat ParametersFormat
        = new(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            memberOptions: SymbolDisplayMemberOptions.IncludeParameters,
            parameterOptions: SymbolDisplayParameterOptions.IncludeName
                              | SymbolDisplayParameterOptions.IncludeType
                              | SymbolDisplayParameterOptions.IncludeModifiers,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
                                  | SymbolDisplayMiscellaneousOptions.UseSpecialTypes
                                  | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

    extension(CodeWriter writer)
    {
        private void AppendHeader(LanguageVersion languageVersion)
        {
            writer.AppendLine("// <auto-generated />").AppendLine();

            if (languageVersion.SupportsNullableReferenceTypes)
                writer.AppendLine("#nullable enable").AppendLine();
        }

        public void AppendInterceptorHeader(LanguageVersion languageVersion)
        {
            writer.AppendHeader(languageVersion);

            writer.AppendLine(
                $$"""
                namespace System.Runtime.CompilerServices
                {
                    [global::Microsoft.CodeAnalysis.Embedded]
                    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
                    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                    {{languageVersion.GeneratedTypeModifier}} sealed class InterceptsLocationAttribute : global::System.Attribute
                    {
                        public InterceptsLocationAttribute(int version, string data)
                        { }
                    }
                }

                namespace Microsoft.CodeAnalysis
                {
                    internal sealed partial class EmbeddedAttribute : global::System.Attribute
                    { }
                }

                """
            );
        }

        public CodeWriter AppendEmbeddedAttributeLine()
            => writer.AppendLine("[global::Microsoft.CodeAnalysis.Embedded]");

        public void AppendInterceptsLocationAttributeLine(InterceptableLocation location)
        {
            writer.Append(location.GetInterceptsLocationAttributeSyntax())
#if DEBUG
                  .Append(" // ").Append(location.GetDisplayLocation())
#endif
                  .AppendLine();
        }
    }
}
