<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>PCRE.Tests.Integration</RootNamespace>
    <PcreNetOutputNativeLibs>true</PcreNetOutputNativeLibs>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <ControlFlowGuard>Guard</ControlFlowGuard>
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
    <!-- <PreferNativeArm64>true</PreferNativeArm64> TODO: Add .NET Framework integration tests -->
  </PropertyGroup>

  <Import Project="../Version.props" />

  <Choose>
    <When Condition="'$(PcreNetIntegrationTest)' == 'true'">
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);PCRENET_INTEGRATION_TEST</DefineConstants>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="PCRE.NET" Version="[$(Version)]" />
      </ItemGroup>
    </When>

    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="../PCRE.NET/PCRE.NET.csproj" />
        <ProjectReference Include="../PCRE.NET.Analyzers/PCRE.NET.Analyzers.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <Import Project="../PCRE.NET/Build/NativeLibs.props" Condition="'$(PcreNetIntegrationTest)' != 'true'" />
  <Import Project="../PCRE.NET/Build/PCRE.NET.targets" Condition="'$(PcreNetIntegrationTest)' != 'true'" />

</Project>
