<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NetCoreTargetFramework>net10.0</NetCoreTargetFramework>
    <TargetFramework Condition="'$(TargetFramework)' == ''">$(NetCoreTargetFramework)</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>PCRE.Tests.Integration</RootNamespace>
    <OutputType>Exe</OutputType>
    <ControlFlowGuard>Guard</ControlFlowGuard>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == '$(NetCoreTargetFramework)'">
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
  </PropertyGroup>

  <!-- Integration Test Mode -->

  <PropertyGroup Condition="'$(PcreNetIntegrationTest)' == 'true'">
    <DefineConstants>$(DefineConstants);PCRENET_INTEGRATION_TEST</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(PcreNetIntegrationTest)' == 'true'">
    <PackageReference Include="PCRE.NET" Version="[$(Version)]" />
  </ItemGroup>

  <!-- Local Test Mode -->

  <ItemGroup Condition="'$(PcreNetIntegrationTest)' != 'true'">
    <ProjectReference Include="../PCRE.NET/PCRE.NET.csproj" />
    <ProjectReference Include="../PCRE.NET.Analyzers/PCRE.NET.Analyzers.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <Import Project="../PCRE.NET/Build/PCRE.NET.targets" Condition="'$(PcreNetIntegrationTest)' != 'true'" />

</Project>
