using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PCRE.Internal;
using PCRE.NET.InternalAnalyzers.Support;

namespace PCRE.NET.InternalAnalyzers;

[Generator]
public class ForwardTo8BitGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> _typeNamesToSuffix =
    [
        "PcreMatchBuffer",
        "PcreRefCallout",
        "PcreRefCalloutFunc",
        "PcreRefGroup",
        "PcreRefMatch"
    ];

    private static readonly Regex _regexCharToByte = new("""\bchar\b""", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly Regex _regexBitSuffix = new("""(?<prefix>\w+)16Bit\b""", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly Regex _regexRemoveAttribute = new("""^[ ]*\[\s*ForwardTo8Bit\s*\][ ]*\r?\n""", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.Multiline);
    private static readonly Regex _regexTypeNamesToSuffix = new("""\bPcre\w+""", RegexOptions.Compiled | RegexOptions.CultureInvariant);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toForward = context.SyntaxProvider
                               .ForAttributeWithMetadataName(
                                   typeof(ForwardTo8BitAttribute).FullName!,
                                   static (node, _) => (SyntaxKind)node.RawKind is SyntaxKind.ClassDeclaration or SyntaxKind.StructDeclaration && node.Parent is not TypeDeclarationSyntax,
                                   static (context, cancellationToken) => GeneratorModel.Create(context, cancellationToken)
                               )
                               .WithLambdaComparer(
                                   static (a, b) => a.RootTypeNode.IsEquivalentTo(b.RootTypeNode),
                                   static i => i.RootTypeNode.Identifier.GetHashCode()
                               );

        context.RegisterSourceOutput(toForward, Generate);
    }

    private static void Generate(SourceProductionContext context, GeneratorModel model)
    {
        context.AddSource(
            $"{model.FileName}.g.cs",
            GenerateTopLevel(model, context.CancellationToken)
        );
    }

    private static string GenerateTopLevel(GeneratorModel model, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var writer = new CodeWriter();

        writer.AppendLine("// <auto-generated />")
              .AppendLine()
              .AppendLine(model.RootTypeNode.SyntaxTree.GetCompilationUnitRoot(cancellationToken).Usings)
              .AppendLine()
              .AppendLine($"namespace {model.RootTypeSymbol.ContainingNamespace.ToDisplayString()};")
              .AppendLine()
              .AppendLine("#nullable enable");

        GenerateType(writer, model, model.RootTypeNode, false, "8Bit", cancellationToken);

        return writer.ToString();
    }

    private static void GenerateType(CodeWriter writer,
                                     GeneratorModel model,
                                     TypeDeclarationSyntax node,
                                     bool isInnerType,
                                     string suffix,
                                     CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        writer.AppendLine()
              .Append(node.Modifiers)
              .Append(node.Modifiers.Any(SyntaxKind.PartialKeyword) ? "" : " partial")
              .Append(' ')
              .Append(node.Keyword)
              .Append(' ')
              .Append(node.Identifier)
              .Append(isInnerType ? "" : suffix)
              .AppendLine();

        using (writer.WriteBlock())
        {
            foreach (var memberNode in node.Members)
            {
                if (model.SemanticModel.GetDeclaredSymbol(memberNode) is not { } memberSymbol)
                    continue;

                if (memberSymbol.GetAttribute(model.AttributeSymbol) is null)
                    continue;

                switch ((SyntaxKind)memberNode.RawKind)
                {
                    case SyntaxKind.MethodDeclaration:
                    case SyntaxKind.PropertyDeclaration:
                    case SyntaxKind.IndexerDeclaration:
                    case SyntaxKind.ConstructorDeclaration:
                    case SyntaxKind.DestructorDeclaration:
                        GenerateMethodOrProperty(writer, model, memberNode, suffix, cancellationToken);
                        break;

                    case SyntaxKind.ClassDeclaration:
                    case SyntaxKind.StructDeclaration:
                        GenerateType(writer, model, (TypeDeclarationSyntax)memberNode, true, suffix, cancellationToken);
                        break;
                }
            }
        }
    }

    private static void GenerateMethodOrProperty(CodeWriter writer,
                                                 GeneratorModel model,
                                                 MemberDeclarationSyntax member,
                                                 string suffix,
                                                 CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var memberText = member.ToString();

        memberText = _regexCharToByte.Replace(memberText, "byte");
        memberText = _regexBitSuffix.Replace(memberText, "${prefix}8Bit");
        memberText = _regexRemoveAttribute.Replace(memberText, "");
        memberText = _regexTypeNamesToSuffix.Replace(memberText, m => _typeNamesToSuffix.Contains(m.Value) ? $"{m.Value}{suffix}" : m.Value);

        writer.AppendLine();

        if (model.SemanticModel.GetDeclaredSymbol(member) is { DeclaredAccessibility: Accessibility.Public or Accessibility.Protected } symbol
            && DocumentationCommentId.CreateDeclarationId(symbol) is { } cref)
        {
            // Work around https://youtrack.jetbrains.com/issue/RIDER-84751
            if (cref.IndexOf('~') is >= 0 and var index)
                cref = cref.Substring(0, index);

            if (!cref.EndsWith("()") && member is MethodDeclarationSyntax { ParameterList.Parameters.Count: 0 })
                cref += "()";

            writer.AppendLine($"""/// <inheritdoc cref="{cref}" />""");
        }

        writer.AppendLine(memberText.Trim());
    }

    private sealed record GeneratorModel(
        TypeDeclarationSyntax RootTypeNode,
        ISymbol RootTypeSymbol,
        INamedTypeSymbol AttributeSymbol,
        SemanticModel SemanticModel,
        string FileName)
    {
        public static GeneratorModel Create(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            return new GeneratorModel(
                (TypeDeclarationSyntax)context.TargetNode,
                context.TargetSymbol,
                context.Attributes[0].AttributeClass!,
                context.SemanticModel,
                Path.GetFileNameWithoutExtension(context.TargetNode.SyntaxTree.FilePath)
            );
        }
    }
}
