using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PCRE.NET.InternalAnalyzers;

[Generator]
public class ForwardTo8BitGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toForward = context.SyntaxProvider
                               .ForAttributeWithMetadataName(
                                   "PCRE.Internal.ForwardTo8BitAttribute",
                                   static (node, _) => (SyntaxKind)node.RawKind is SyntaxKind.ClassDeclaration or SyntaxKind.StructDeclaration,
                                   static (context, _) => TypeModel.From(context)
                               );

        context.RegisterSourceOutput(toForward, ForwardType);
    }

    private static void ForwardType(SourceProductionContext context, TypeModel model)
    {
        context.AddSource(
            $"{model.Node.Identifier}.g.cs",
            GenerateType(model, "Utf8", context.CancellationToken)
        );
    }

    private static string GenerateType(TypeModel model, string suffix, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var writer = new CodeWriter();
        var (node, _) = model;

        writer.AppendLine("// <auto-generated />")
              .AppendLine()
              .AppendLine(node.SyntaxTree.GetCompilationUnitRoot(cancellationToken).Usings)
              .AppendLine()
              .AppendLine($"namespace {model.Namespace};")
              .AppendLine()
              .AppendLine("#nullable enable")
              .AppendLine();

        writer.Append(node.Modifiers)
              .Append(node.Modifiers.Any(SyntaxKind.PartialKeyword) ? "" : " partial")
              .Append(' ')
              .Append(node.Keyword)
              .Append(' ')
              .Append(node.Identifier)
              .Append(suffix)
              .AppendLine();

        using (writer.WriteBlock())
        {
            foreach (var member in node.Members)
            {
                if (!HasAttribute(member, "ForwardTo8Bit"))
                    continue;

                GenerateMember(writer, member, suffix, cancellationToken);
            }
        }

        return writer.ToString();
    }

    private static void GenerateMember(CodeWriter writer, MemberDeclarationSyntax member, string suffix, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var memberText = member.ToFullString();
        memberText = _regexCharToByte.Replace(memberText, "byte");
        memberText = _regexRemoveAttribute.Replace(memberText, "");
        memberText = _regexTypeNamesToSuffix.Replace(memberText, m => _typeNamesToSuffix.Contains(m.Value) ? $"{m.Value}{suffix}" : m.Value);

        writer.Append(memberText);
    }

    private static readonly Regex _regexCharToByte = new("""\bchar\b""", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly Regex _regexRemoveAttribute = new("""^[ ]*\[\s*ForwardTo8Bit\s*\][ ]*\r?\n""", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.Multiline);
    private static readonly Regex _regexTypeNamesToSuffix = new("""\bPcre\w+""", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly HashSet<string> _typeNamesToSuffix = ["PcreRefGroup", "PcreRefCalloutFunc", "PcreMatchBuffer"];

    private static bool HasAttribute(MemberDeclarationSyntax member, string attributeName)
    {
        foreach (var attributeList in member.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (attribute.Name.ToString() == attributeName)
                    return true;
            }
        }

        return false;
    }

    private record TypeModel(TypeDeclarationSyntax Node, string Namespace)
    {
        public static TypeModel From(GeneratorAttributeSyntaxContext context)
        {
            return new TypeModel(
                (TypeDeclarationSyntax)context.TargetNode,
                context.TargetSymbol.ContainingNamespace.ToDisplayString()
            );
        }
    }
}
