using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PCRE.NET.InternalAnalyzers;

[Generator]
public class ForwardTo8BitGenerator : IIncrementalGenerator
{
    private const string _attributeFullName = "PCRE.Internal.ForwardTo8BitAttribute";

    private static readonly HashSet<string> _typeNamesToSuffix =
    [
        "PcreMatchBuffer",
        "PcreRefCallout",
        "PcreRefCalloutFunc",
        "PcreRefGroup",
        "PcreRefMatch"
    ];

    private static readonly Regex _regexCharToByte = new("""\bchar\b""", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly Regex _regexBitSuffix = new("""(?<prefix>\w+)16Bit\b""", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly Regex _regexRemoveAttribute = new("""^[ ]*\[\s*ForwardTo8Bit\s*\][ ]*\r?\n""", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.Multiline);
    private static readonly Regex _regexTypeNamesToSuffix = new("""\bPcre\w+""", RegexOptions.Compiled | RegexOptions.CultureInvariant);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toForward = context.SyntaxProvider
                               .ForAttributeWithMetadataName(
                                   _attributeFullName,
                                   static (node, _) => (SyntaxKind)node.RawKind is SyntaxKind.ClassDeclaration or SyntaxKind.StructDeclaration && node.Parent is not TypeDeclarationSyntax,
                                   static (context, cancellationToken) => GeneratorModel.Create(context, cancellationToken)
                               );

        context.RegisterSourceOutput(toForward, Generate);
    }

    private static void Generate(SourceProductionContext context, GeneratorModel model)
    {
        context.AddSource(
            $"{model.FileName}.g.cs",
            GenerateTopLevel(model, context.CancellationToken)
        );
    }

    private static string GenerateTopLevel(GeneratorModel model, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var writer = new CodeWriter();

        writer.AppendLine("// <auto-generated />")
              .AppendLine()
              .AppendLine(model.Usings)
              .AppendLine()
              .AppendLine($"namespace {model.Namespace};")
              .AppendLine()
              .AppendLine("#nullable enable");

        GenerateType(writer, model.Type, false, "Utf8", cancellationToken);

        return writer.ToString();
    }

    private static void GenerateType(CodeWriter writer,
                                     TypeModel type,
                                     bool isInnerType,
                                     string suffix,
                                     CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var node = (TypeDeclarationSyntax)type.Node;

        writer.AppendLine()
              .Append(node.Modifiers)
              .Append(node.Modifiers.Any(SyntaxKind.PartialKeyword) ? "" : " partial")
              .Append(' ')
              .Append(node.Keyword)
              .Append(' ')
              .Append(node.Identifier)
              .Append(isInnerType ? "" : suffix)
              .AppendLine();

        using (writer.WriteBlock())
        {
            foreach (var member in type.Members)
            {
                switch ((SyntaxKind)member.Node.RawKind)
                {
                    case SyntaxKind.MethodDeclaration:
                    case SyntaxKind.PropertyDeclaration:
                    case SyntaxKind.IndexerDeclaration:
                    case SyntaxKind.ConstructorDeclaration:
                    case SyntaxKind.DestructorDeclaration:
                        GenerateMethodOrProperty(writer, member, suffix, cancellationToken);
                        break;

                    case SyntaxKind.ClassDeclaration:
                    case SyntaxKind.StructDeclaration:
                        GenerateType(writer, (TypeModel)member, true, suffix, cancellationToken);
                        break;
                }
            }
        }
    }

    private static void GenerateMethodOrProperty(CodeWriter writer,
                                                 MemberModel member,
                                                 string suffix,
                                                 CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var memberText = member.Node.ToString();

        memberText = _regexCharToByte.Replace(memberText, "byte");
        memberText = _regexBitSuffix.Replace(memberText, "${prefix}8Bit");
        memberText = _regexRemoveAttribute.Replace(memberText, "");
        memberText = _regexTypeNamesToSuffix.Replace(memberText, m => _typeNamesToSuffix.Contains(m.Value) ? $"{m.Value}{suffix}" : m.Value);

        // Work around https://youtrack.jetbrains.com/issue/RIDER-84751
        var cref = member.Cref ?? string.Empty;
        if (cref.IndexOf('~') is >= 0 and var index)
            cref = cref.Substring(0, index);

        writer.AppendLine()
              .Append($"""/// <inheritdoc cref="{cref}" />""").Append('\n')
              .AppendLine(memberText);
    }

    private static bool HasAttribute(ISymbol symbol, ISymbol attribute)
    {
        foreach (var attributeData in symbol.GetAttributes())
        {
            if (SymbolEqualityComparer.Default.Equals(attributeData.AttributeClass, attribute))
                return true;
        }

        return false;
    }

    private record GeneratorModel(TypeModel Type, string FileName, SyntaxList<UsingDirectiveSyntax> Usings, string Namespace)
    {
        public static GeneratorModel Create(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            return new GeneratorModel(
                TypeModel.Create(
                    (TypeDeclarationSyntax)context.TargetNode,
                    (INamedTypeSymbol)context.TargetSymbol,
                    context.SemanticModel,
                    context.Attributes[0].AttributeClass!,
                    cancellationToken
                ),
                Path.GetFileNameWithoutExtension(context.TargetNode.SyntaxTree.FilePath),
                context.TargetNode.SyntaxTree.GetCompilationUnitRoot(cancellationToken).Usings,
                context.TargetSymbol.ContainingNamespace.ToDisplayString()
            );
        }
    }

    private record MemberModel
    {
        public MemberDeclarationSyntax Node { get; }
        public string? Cref { get; }

        protected MemberModel(MemberDeclarationSyntax node, ISymbol symbol)
        {
            Node = node;
            Cref = DocumentationCommentId.CreateDeclarationId(symbol);
        }

        protected static MemberModel Create(MemberDeclarationSyntax member,
                                            ISymbol symbol,
                                            SemanticModel semanticModel,
                                            INamedTypeSymbol attributeSymbol,
                                            CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (member is TypeDeclarationSyntax type)
                return TypeModel.Create(type, (INamedTypeSymbol)symbol, semanticModel, attributeSymbol, cancellationToken);

            return new MemberModel(member, symbol);
        }
    }

    private sealed record TypeModel : MemberModel
    {
        public ImmutableArray<MemberModel> Members { get; }

        private TypeModel(MemberDeclarationSyntax node, ISymbol symbol, IEnumerable<MemberModel> members)
            : base(node, symbol)
        {
            Members = [..members];
        }

        public static TypeModel Create(TypeDeclarationSyntax type,
                                       INamedTypeSymbol symbol,
                                       SemanticModel semanticModel,
                                       INamedTypeSymbol attributeSymbol,
                                       CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var members = new List<MemberModel>();

            foreach (var memberSyntax in type.Members)
            {
                if (semanticModel.GetDeclaredSymbol(memberSyntax) is not { } memberSymbol)
                    continue;

                if (!HasAttribute(memberSymbol, attributeSymbol))
                    continue;

                members.Add(
                    MemberModel.Create(
                        memberSyntax,
                        memberSymbol,
                        semanticModel,
                        attributeSymbol,
                        cancellationToken
                    )
                );
            }

            return new TypeModel(type, symbol, members);
        }
    }
}
