//HintName: PcreCallsInterceptor.g.cs
// <auto-generated>
//   This file was generated by PCRE.NET to provide additional optimizations.
//   If it causes issues, you can disable its generation by adding the
//   following property to a <PropertyGroup /> in the csproj file:
//   <PcreNetInterceptors>false</PcreNetInterceptors>
// </auto-generated>

#nullable enable

namespace System.Runtime.CompilerServices
{
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        { }
    }
}

namespace Microsoft.CodeAnalysis
{
    internal sealed partial class EmbeddedAttribute : global::System.Attribute
    { }
}

namespace PCRE.Generated
{
    [global::Microsoft.CodeAnalysis.Embedded]
    file static class PcreCallsInterceptor
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace0_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc0);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace1_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc1);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace2_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc2);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace3_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc3);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace4_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc4);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace5_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc5);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace6_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc6);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace7_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc7);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace8_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc8);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace9_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: match => _replacementFunc9(match, subject));

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace10_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: match => _replacementFunc10(match, subject));

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace11_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: match => _replacementFunc11(match, subject));

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace12_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc12);

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc0
            = static _ => string.Empty;

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc1
            = static _ => "replacement";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc2
            = static match => $"a $ b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc3
            = static match => $"a {GetGroup(match, 0)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc4
            = static match => $"a {GetGroup(match, 0) ?? "$0"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc5
            = static match => $"a {GetGroup(match, 1) ?? "$1"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc6
            = static match => $"a {GetGroup(match, 2) ?? "$2"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc7
            = static match => $"a {GetGroup(match, "group", -1) ?? "${group}"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc8
            = static match => $"a {GetGroup(match, "other", -1) ?? "${other}"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string, string> _replacementFunc9
            = static (match, subject) => $"a {subject.Substring(0, match.Index)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string, string> _replacementFunc10
            = static (match, subject) => $"a {subject.Substring(match.EndIndex)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string, string> _replacementFunc11
            = static (match, subject) => $"a {subject} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc12
            = static match => $"a {GetLastMatchedGroup(match)} b";

        private static string? GetGroup(global::PCRE.PcreMatch match, int index)
            => match.TryGetGroup(index, out var group) ? group.Value : null;

        private static string? GetGroup(global::PCRE.PcreMatch match, string name, int index)
            => match.TryGetGroup(name, out var group) || match.TryGetGroup(index, out group) ? group.Value : null;

        private static string GetLastMatchedGroup(global::PCRE.PcreMatch match)
        {
            for (var i = match.CaptureCount; i > 0; --i)
            {
                if (match.TryGetGroup(i, out var group) && group.Success)
                    return group.Value;
            }

            return string.Empty;
        }
    }
}
