//HintName: PcreCallsInterceptor.g.cs
// <auto-generated>
//   This file was generated by PCRE.NET to provide additional optimizations.
//   If it causes issues, you can disable its generation by adding the
//   following property to a <PropertyGroup /> in the csproj file:
//   <PcreNetInterceptors>false</PcreNetInterceptors>
// </auto-generated>

#nullable enable

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        { }
    }
}

namespace PCRE.Generated
{
    file static class PcreCallsInterceptor
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace0_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc0);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace1_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc1);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace2_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc2);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace3_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc3);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace4_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc4);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace5_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc5);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace6_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc6);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace7_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc7);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace8_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc8);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace9_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc9);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace10_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: match => _replacementFunc10(match, subject));

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace11_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: match => _replacementFunc11(match, subject));

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace12_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: match => _replacementFunc12(match, subject));

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace13_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc13);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace14_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc14);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace15_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc15);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace16_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc16);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace17_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc17);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace18_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc18);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace19_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc19);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace20_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc20);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace21_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc21);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Replace22_Call0(this global::PCRE.PcreRegex regex, string subject, string replacement)
            => regex.Replace(subject: subject, replacementFunc: _replacementFunc22);

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc0
            = static _ => "";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc1
            = static _ => "replacement";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc2
            = static _ => "a $ b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc3
            = static match => $"a {GetGroup(match, 0)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc4
            = static match => $"a {GetGroup(match, 0) ?? "$0"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc5
            = static match => $"a {GetGroup(match, 1) ?? "$1"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc6
            = static match => $"a {GetGroup(match, 2) ?? "$2"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc7
            = static match => $"a {GetGroup(match, "group") ?? "${group}"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc8
            = static match => $"a {GetGroup(match, "other") ?? "${other}"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc9
            = static match => $"a {GetGroup(match, "1", 1) ?? "${1}"} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string, string> _replacementFunc10
            = static (match, subject) => $"a {subject.Substring(0, match.Index)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string, string> _replacementFunc11
            = static (match, subject) => $"a {subject.Substring(match.EndIndex)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string, string> _replacementFunc12
            = static (match, subject) => $"a {subject} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc13
            = static match => $"a {GetLastMatchedGroup(match)} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc14
            = static _ => "a \" b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc15
            = static _ => "a {} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc16
            = static _ => "a \n b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc17
            = static _ => "a \r\n b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc18
            = static match => $"a {GetGroup(match, 1) ?? "$1"} \" b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc19
            = static match => $"a {GetGroup(match, 1) ?? "$1"} {{}} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc20
            = static match => $"a {GetGroup(match, 1) ?? "$1"} {{{{}}}} b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc21
            = static match => $"a {GetGroup(match, 1) ?? "$1"} \n b";

        private static readonly global::System.Func<global::PCRE.PcreMatch, string> _replacementFunc22
            = static match => $"a {GetGroup(match, 1) ?? "$1"} \r\n b";

        private static string? GetGroup(global::PCRE.PcreMatch match, int index)
            => match.TryGetGroup(index, out var group) ? group.Value : null;

        private static string? GetGroup(global::PCRE.PcreMatch match, string name)
            => match.TryGetGroup(name, out var group) ? group.Value : null;

        private static string? GetGroup(global::PCRE.PcreMatch match, string name, int index)
            => match.TryGetGroup(name, out var group) || match.TryGetGroup(index, out group) ? group.Value : null;

        private static string GetLastMatchedGroup(global::PCRE.PcreMatch match)
        {
            for (var i = match.CaptureCount; i > 0; --i)
            {
                if (match.TryGetGroup(i, out var group) && group.Success)
                    return group.Value;
            }

            return string.Empty;
        }
    }
}
