//HintName: StaticMatchInterceptor.g.cs
// <auto-generated />

#nullable enable

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace PCRE.Generated
{
    file static class StaticMatchInterceptor
    {
        private static global::PCRE.PcreRegex? _regex0;
        private static global::PCRE.PcreRegex Regex0 => _regex0 ??= new global::PCRE.PcreRegex(
            "pattern",
            (global::PCRE.PcreOptions)0x0000000000000000
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Intercept0_IsMatch(string subject, string pattern)
            => Regex0.IsMatch(subject: subject);

    }
}
