//HintName: StaticMatchInterceptor.g.cs
// <auto-generated />

#nullable enable

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace PCRE.Generated
{
    file static class StaticMatchInterceptor
    {
        private static global::PCRE.PcreRegex? _regex0;
        private static global::PCRE.PcreRegex Regex0 => _regex0 ??= new global::PCRE.PcreRegex(
            "pattern",
            (global::PCRE.PcreOptions)0x0000000000000000
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Regex0_Call0_IsMatch(string subject, string pattern)
            => Regex0.IsMatch(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex0_Call1_Match(string subject, string pattern)
            => Regex0.Match(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<global::PCRE.PcreMatch> Regex0_Call2_Matches(string subject, string pattern)
            => Regex0.Matches(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex0_Call3_Replace(string subject, string pattern, string replacement)
            => Regex0.Replace(subject: subject, replacement: replacement);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex0_Call4_Replace(string subject, string pattern, global::System.Func<global::PCRE.PcreMatch, string> replacementFunc)
            => Regex0.Replace(subject: subject, replacementFunc: replacementFunc);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<string> Regex0_Call5_Split(string subject, string pattern)
            => Regex0.Split(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<string> Regex0_Call6_Split(string subject, string pattern, int count)
            => Regex0.Split(subject: subject, count: count);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex0_Call7_Substitute(string subject, string pattern, string replacement)
            => Regex0.Substitute(subject: subject, replacement: replacement);

        private static global::PCRE.PcreRegex? _regex1;
        private static global::PCRE.PcreRegex Regex1 => _regex1 ??= new global::PCRE.PcreRegex(
            "pattern",
            (global::PCRE.PcreOptions)0x0000000000000008
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Regex1_Call0_IsMatch(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex1.IsMatch(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Regex1_Call1_IsMatch(string subject, string pattern, global::PCRE.PcreOptions options, int startIndex)
            => Regex1.IsMatch(subject: subject, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex1_Call2_Match(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex1.Match(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex1_Call3_Match(string subject, string pattern, global::PCRE.PcreOptions options, int startIndex)
            => Regex1.Match(subject: subject, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<global::PCRE.PcreMatch> Regex1_Call4_Matches(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex1.Matches(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<global::PCRE.PcreMatch> Regex1_Call5_Matches(string subject, string pattern, global::PCRE.PcreOptions options, int startIndex)
            => Regex1.Matches(subject: subject, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call6_Replace(string subject, string pattern, string replacement, global::PCRE.PcreOptions options)
            => Regex1.Replace(subject: subject, replacement: replacement);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call7_Replace(string subject, string pattern, string replacement, global::PCRE.PcreOptions options, int count)
            => Regex1.Replace(subject: subject, replacement: replacement, count: count);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call8_Replace(string subject, string pattern, string replacement, global::PCRE.PcreOptions options, int count, int startIndex)
            => Regex1.Replace(subject: subject, replacement: replacement, count: count, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call9_Replace(string subject, string pattern, global::System.Func<global::PCRE.PcreMatch, string> replacementFunc, global::PCRE.PcreOptions options)
            => Regex1.Replace(subject: subject, replacementFunc: replacementFunc);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call10_Replace(string subject, string pattern, global::System.Func<global::PCRE.PcreMatch, string> replacementFunc, global::PCRE.PcreOptions options, int count)
            => Regex1.Replace(subject: subject, replacementFunc: replacementFunc, count: count);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call11_Replace(string subject, string pattern, global::System.Func<global::PCRE.PcreMatch, string> replacementFunc, global::PCRE.PcreOptions options, int count, int startIndex)
            => Regex1.Replace(subject: subject, replacementFunc: replacementFunc, count: count, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<string> Regex1_Call12_Split(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex1.Split(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<string> Regex1_Call13_Split(string subject, string pattern, global::PCRE.PcreOptions options, global::PCRE.PcreSplitOptions splitOptions)
            => Regex1.Split(subject: subject, splitOptions: splitOptions);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<string> Regex1_Call14_Split(string subject, string pattern, global::PCRE.PcreOptions options, global::PCRE.PcreSplitOptions splitOptions, int count)
            => Regex1.Split(subject: subject, splitOptions: splitOptions, count: count);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::System.Collections.Generic.IEnumerable<string> Regex1_Call15_Split(string subject, string pattern, global::PCRE.PcreOptions options, global::PCRE.PcreSplitOptions splitOptions, int count, int startIndex)
            => Regex1.Split(subject: subject, splitOptions: splitOptions, count: count, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static string Regex1_Call16_Substitute(string subject, string pattern, string replacement, global::PCRE.PcreOptions options, global::PCRE.PcreSubstituteOptions substituteOptions)
            => Regex1.Substitute(subject: subject, replacement: replacement, substituteOptions: substituteOptions);

    }
}
