//HintName: StaticMatchInterceptor.g.cs
// <auto-generated />

#nullable enable

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace PCRE.Generated
{
    file static class StaticMatchInterceptor
    {
        private static global::PCRE.PcreRegex? _regex0;
        private static global::PCRE.PcreRegex Regex0 => _regex0 ??= new global::PCRE.PcreRegex(
            "pattern",
            (global::PCRE.PcreOptions)0x0000000000000000
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex0_Call0_Match(string subject, string pattern)
            => Regex0.Match(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Regex0_Call1_IsMatch(string subject, string pattern)
            => Regex0.IsMatch(subject: subject);

        private static global::PCRE.PcreRegex? _regex1;
        private static global::PCRE.PcreRegex Regex1 => _regex1 ??= new global::PCRE.PcreRegex(
            "pattern",
            (global::PCRE.PcreOptions)0x0000000000000008
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex1_Call0_Match(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex1.Match(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Regex1_Call1_IsMatch(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex1.IsMatch(subject: subject);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex1_Call2_Match(string subject, string pattern, global::PCRE.PcreOptions options, int startIndex)
            => Regex1.Match(subject: subject, startIndex: startIndex);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static bool Regex1_Call3_IsMatch(string subject, string pattern, global::PCRE.PcreOptions options, int startIndex)
            => Regex1.IsMatch(subject: subject, startIndex: startIndex);

        private static global::PCRE.PcreRegex? _regex2;
        private static global::PCRE.PcreRegex Regex2 => _regex2 ??= new global::PCRE.PcreRegex(
            "pattern",
            (global::PCRE.PcreOptions)0x0000000100000000
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex2_Call0_Match(string subject, string pattern, global::PCRE.PcreOptions options)
            => Regex2.Match(subject: subject);

        private static global::PCRE.PcreRegex? _regex3;
        private static global::PCRE.PcreRegex Regex3 => _regex3 ??= new global::PCRE.PcreRegex(
            "pattern2",
            (global::PCRE.PcreOptions)0x0000000000000000
        );

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(0, "...")]
        public static global::PCRE.PcreMatch Regex3_Call0_Match(string subject, string pattern)
            => Regex3.Match(subject: subject);

    }
}
