<Project>

  <Import Project="Version.props" />

  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AnalysisLevel>10.0</AnalysisLevel>
    <AnalysisModeStyle>None</AnalysisModeStyle>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Prefer32Bit>false</Prefer32Bit>
    <DefaultItemExcludes>$(DefaultItemExcludes);*.DotSettings;*.ncrunchproject</DefaultItemExcludes>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' != ''">true</ContinuousIntegrationBuild>
    <NoWarn>$(NoWarn);CA1510</NoWarn>
    <NetFrameworkTarget>net481</NetFrameworkTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(NCrunch)' == '1'">
    <EnableSourceLink>false</EnableSourceLink>
    <EnableSourceControlManagerQueries>false</EnableSourceControlManagerQueries>
  </PropertyGroup>

  <ItemGroup>
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.x86.dll" RuntimeIdentifier="win-x86" />
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.x64.dll" RuntimeIdentifier="win-x64" />
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.arm64.dll" RuntimeIdentifier="win-arm64" />
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.x64.so" RuntimeIdentifier="linux-x64" />
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.arm64.so" RuntimeIdentifier="linux-arm64" />
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.arm64.dylib" RuntimeIdentifier="osx-arm64" />
    <PcreNetNativeLib Include="$(MSBuildThisFileDirectory)..\lib\PCRE.NET.Native.x64.dylib" RuntimeIdentifier="osx-x64" />
  </ItemGroup>

  <ItemGroup>
    <PcreNetNativeLib Update="@(PcreNetNativeLib)" Exists="$([System.IO.File]::Exists('%(FullPath)'))" Visible="false" />
  </ItemGroup>

</Project>
