<Project>

  <PropertyGroup Condition="'$(PcreNetTestBuild)' == 'true'">
    <DefineConstants>$(DefineConstants);TEST_BUILD</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants Condition="'$(ExpectPlatform)' == 'x86'">$(DefineConstants);EXPECT_X86</DefineConstants>
    <DefineConstants Condition="'$(ExpectPlatform)' == 'x64'">$(DefineConstants);EXPECT_X64</DefineConstants>
    <DefineConstants Condition="'$(ExpectPlatform)' == 'arm64'">$(DefineConstants);EXPECT_ARM64</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(OutputType)' == 'Exe' or '$(IsTestProject)' == 'true'">
    <None Include="@(PcreNetNativeLib->WithMetadataValue('Exists', 'true'))"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'"
          Link="%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          Visible="false" />

    <None Include="@(PcreNetNativeLib->WithMetadataValue('Exists', 'true')->WithMetadataValue('RuntimeIdentifier', '$(RuntimeIdentifier)'))"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'"
          Link="PCRE.NET.Native%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          Visible="false" />
  </ItemGroup>

</Project>
