<Project>

  <ItemGroup Condition="'$(OutputType)' == 'Exe' or '$(IsTestProject)' == 'true'">
    <None Include="@(PcreNetNativeLib->Exists())"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'"
          Link="%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          Visible="false" />

    <None Include="@(PcreNetNativeLib->Exists()->WithMetadataValue('RuntimeIdentifier', '$(RuntimeIdentifier)'))"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'"
          Link="PCRE.NET.Native%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          Visible="false" />
  </ItemGroup>

</Project>
