<Project>

  <ItemGroup>
    <PcreNetNativeLibRid Include="win-x86" />
    <PcreNetNativeLibRid Include="win-x64" />
    <PcreNetNativeLibRid Include="win-arm64" />
    <PcreNetNativeLibRid Include="linux-x64" />
    <PcreNetNativeLibRid Include="linux-arm64" />
    <PcreNetNativeLibRid Include="linux-musl-x64" />
    <PcreNetNativeLibRid Include="osx-arm64" />
    <PcreNetNativeLibRid Include="osx-x64" />
  </ItemGroup>

  <ItemGroup>
    <PcreNetNativeLibRid Update="win-*" LibExtension="dll" />
    <PcreNetNativeLibRid Update="linux-*" LibExtension="so" />
    <PcreNetNativeLibRid Update="osx-*" LibExtension="dylib" />

    <PcreNetNativeLibRid Update="@(PcreNetNativeLibRid)"
                         OperatingSystem="$([System.Text.RegularExpressions.Regex]::Match('%(Identity)', '^[^-]+').Value)"
                         Architecture="$([System.Text.RegularExpressions.Regex]::Match('%(Identity)', '[^-]+$').Value)"
                         RuntimeIdentifier="%(Identity)"
                         Visible="false" />

    <PcreNetNativeLib Include="@(PcreNetNativeLibRid->'$(MSBuildThisFileDirectory)../lib/PCRE.NET.Native.%(Identity).%(LibExtension)')" />

    <PcreNetNativeLibRid Remove="@(PcreNetNativeLibRid)" />
  </ItemGroup>

</Project>
