<Project>

  <ItemGroup Condition="'$(OutputType)' == 'Exe' or '$(IsTestProject)' == 'true'">
    <None Include="@(PcreNetNativeLib->Exists()->WithMetadataValue('OperatingSystem', 'win'))"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'"
          Link="PCRE.NET.Native.%(Architecture)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />

    <None Include="@(PcreNetNativeLib->Exists()->WithMetadataValue('RuntimeIdentifier', '$(RuntimeIdentifier)'))"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'"
          Link="PCRE.NET.Native%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
