//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;
using System.Security;

namespace PCRE.Internal
{
    unsafe partial class Native
    {
        public static void test()
            => _impl.test();

        public static void compile(ref compile_input input, out compile_result result)
            => _impl.compile(ref input, out result);

        public static void code_free(IntPtr code)
            => _impl.code_free(code);


        private abstract class LibImpl
        {
            public abstract void test();
            public abstract void compile(ref compile_input input, out compile_result result);
            public abstract void code_free(IntPtr code);
        }

        [SuppressUnmanagedCodeSecurity]
        private class WinImpl : LibImpl
        {
            public override void test()
                => pcrenet_test();

            [DllImport("PCRE.NET.Native.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_test();

            public override void compile(ref compile_input input, out compile_result result)
                => pcrenet_compile(ref input, out result);

            [DllImport("PCRE.NET.Native.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_compile(ref compile_input input, out compile_result result);

            public override void code_free(IntPtr code)
                => pcrenet_code_free(code);

            [DllImport("PCRE.NET.Native.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_code_free(IntPtr code);

        }

        [SuppressUnmanagedCodeSecurity]
        private class Win32Impl : LibImpl
        {
            public override void test()
                => pcrenet_test();

            [DllImport("PCRE.NET.Native.x86.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_test();

            public override void compile(ref compile_input input, out compile_result result)
                => pcrenet_compile(ref input, out result);

            [DllImport("PCRE.NET.Native.x86.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_compile(ref compile_input input, out compile_result result);

            public override void code_free(IntPtr code)
                => pcrenet_code_free(code);

            [DllImport("PCRE.NET.Native.x86.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_code_free(IntPtr code);

        }

        [SuppressUnmanagedCodeSecurity]
        private class Win64Impl : LibImpl
        {
            public override void test()
                => pcrenet_test();

            [DllImport("PCRE.NET.Native.x64.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_test();

            public override void compile(ref compile_input input, out compile_result result)
                => pcrenet_compile(ref input, out result);

            [DllImport("PCRE.NET.Native.x64.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_compile(ref compile_input input, out compile_result result);

            public override void code_free(IntPtr code)
                => pcrenet_code_free(code);

            [DllImport("PCRE.NET.Native.x64.dll", CallingConvention = CallingConvention.Cdecl)]
            private static extern void pcrenet_code_free(IntPtr code);

        }

    }
}
