//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCRE.Internal
{
    internal static class PcreConstants
    {
        public const uint ANCHORED = 0x80000000;
        public const uint NO_UTF_CHECK = 0x40000000;
        public const uint ENDANCHORED = 0x20000000;
        public const uint ALLOW_EMPTY_CLASS = 0x00000001;
        public const uint ALT_BSUX = 0x00000002;
        public const uint AUTO_CALLOUT = 0x00000004;
        public const uint CASELESS = 0x00000008;
        public const uint DOLLAR_ENDONLY = 0x00000010;
        public const uint DOTALL = 0x00000020;
        public const uint DUPNAMES = 0x00000040;
        public const uint EXTENDED = 0x00000080;
        public const uint FIRSTLINE = 0x00000100;
        public const uint MATCH_UNSET_BACKREF = 0x00000200;
        public const uint MULTILINE = 0x00000400;
        public const uint NEVER_UCP = 0x00000800;
        public const uint NEVER_UTF = 0x00001000;
        public const uint NO_AUTO_CAPTURE = 0x00002000;
        public const uint NO_AUTO_POSSESS = 0x00004000;
        public const uint NO_DOTSTAR_ANCHOR = 0x00008000;
        public const uint NO_START_OPTIMIZE = 0x00010000;
        public const uint UCP = 0x00020000;
        public const uint UNGREEDY = 0x00040000;
        public const uint UTF = 0x00080000;
        public const uint NEVER_BACKSLASH_C = 0x00100000;
        public const uint ALT_CIRCUMFLEX = 0x00200000;
        public const uint ALT_VERBNAMES = 0x00400000;
        public const uint USE_OFFSET_LIMIT = 0x00800000;
        public const uint EXTENDED_MORE = 0x01000000;
        public const uint LITERAL = 0x02000000;
        public const uint EXTRA_ALLOW_SURROGATE_ESCAPES = 0x00000001;
        public const uint EXTRA_BAD_ESCAPE_IS_LITERAL = 0x00000002;
        public const uint EXTRA_MATCH_WORD = 0x00000004;
        public const uint EXTRA_MATCH_LINE = 0x00000008;
        public const uint JIT_COMPLETE = 0x00000001;
        public const uint JIT_PARTIAL_SOFT = 0x00000002;
        public const uint JIT_PARTIAL_HARD = 0x00000004;
        public const uint NOTBOL = 0x00000001;
        public const uint NOTEOL = 0x00000002;
        public const uint NOTEMPTY = 0x00000004;
        public const uint NOTEMPTY_ATSTART = 0x00000008;
        public const uint PARTIAL_SOFT = 0x00000010;
        public const uint PARTIAL_HARD = 0x00000020;
        public const uint DFA_RESTART = 0x00000040;
        public const uint DFA_SHORTEST = 0x00000080;
        public const uint SUBSTITUTE_GLOBAL = 0x00000100;
        public const uint SUBSTITUTE_EXTENDED = 0x00000200;
        public const uint SUBSTITUTE_UNSET_EMPTY = 0x00000400;
        public const uint SUBSTITUTE_UNKNOWN_UNSET = 0x00000800;
        public const uint SUBSTITUTE_OVERFLOW_LENGTH = 0x00001000;
        public const uint NO_JIT = 0x00002000;
        public const uint CONVERT_UTF = 0x00000001;
        public const uint CONVERT_NO_UTF_CHECK = 0x00000002;
        public const uint CONVERT_POSIX_BASIC = 0x00000004;
        public const uint CONVERT_POSIX_EXTENDED = 0x00000008;
        public const uint CONVERT_GLOB = 0x00000010;
        public const uint CONVERT_GLOB_NO_WILD_SEPARATOR = 0x00000030;
        public const uint CONVERT_GLOB_NO_STARSTAR = 0x00000050;
        public const uint NEWLINE_CR = 1;
        public const uint NEWLINE_LF = 2;
        public const uint NEWLINE_CRLF = 3;
        public const uint NEWLINE_ANY = 4;
        public const uint NEWLINE_ANYCRLF = 5;
        public const uint NEWLINE_NUL = 6;
        public const uint BSR_UNICODE = 1;
        public const uint BSR_ANYCRLF = 2;
        public const uint INFO_ALLOPTIONS = 0;
        public const uint INFO_ARGOPTIONS = 1;
        public const uint INFO_BACKREFMAX = 2;
        public const uint INFO_BSR = 3;
        public const uint INFO_CAPTURECOUNT = 4;
        public const uint INFO_FIRSTCODEUNIT = 5;
        public const uint INFO_FIRSTCODETYPE = 6;
        public const uint INFO_FIRSTBITMAP = 7;
        public const uint INFO_HASCRORLF = 8;
        public const uint INFO_JCHANGED = 9;
        public const uint INFO_JITSIZE = 10;
        public const uint INFO_LASTCODEUNIT = 11;
        public const uint INFO_LASTCODETYPE = 12;
        public const uint INFO_MATCHEMPTY = 13;
        public const uint INFO_MATCHLIMIT = 14;
        public const uint INFO_MAXLOOKBEHIND = 15;
        public const uint INFO_MINLENGTH = 16;
        public const uint INFO_NAMECOUNT = 17;
        public const uint INFO_NAMEENTRYSIZE = 18;
        public const uint INFO_NAMETABLE = 19;
        public const uint INFO_NEWLINE = 20;
        public const uint INFO_DEPTHLIMIT = 21;
        public const uint INFO_SIZE = 22;
        public const uint INFO_HASBACKSLASHC = 23;
        public const uint INFO_FRAMESIZE = 24;
        public const uint INFO_HEAPLIMIT = 25;
        public const uint INFO_EXTRAOPTIONS = 26;
        public const uint CONFIG_BSR = 0;
        public const uint CONFIG_JIT = 1;
        public const uint CONFIG_JITTARGET = 2;
        public const uint CONFIG_LINKSIZE = 3;
        public const uint CONFIG_MATCHLIMIT = 4;
        public const uint CONFIG_NEWLINE = 5;
        public const uint CONFIG_PARENSLIMIT = 6;
        public const uint CONFIG_DEPTHLIMIT = 7;
        public const uint CONFIG_UNICODE = 9;
        public const uint CONFIG_UNICODE_VERSION = 10;
        public const uint CONFIG_VERSION = 11;
        public const uint CONFIG_HEAPLIMIT = 12;
        public const uint CONFIG_NEVER_BACKSLASH_C = 13;
        public const uint CONFIG_COMPILED_WIDTHS = 14;
        public const uint CALLOUT_STARTMATCH = 0x00000001;
        public const uint CALLOUT_BACKTRACK = 0x00000002;
    }
}
