<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;$(NetFrameworkTarget)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <RootNamespace>PCRE.Tests</RootNamespace>
    <DefineConstants Condition="'$(ForceNetStandard)' == 'true'">$(DefineConstants);FORCE_NET_STANDARD</DefineConstants>
    <UseCurrentRuntimeIdentifier Condition="'$(TargetFramework)' != '$(NetFrameworkTarget)' and '$(PlatformTarget)' == ''">true</UseCurrentRuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PcreNetTestBuild)' != 'true'">
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\PCRE.NET.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PCRE.NET.Analyzers\PCRE.NET.Analyzers.csproj" />
    <ProjectReference Include="..\PCRE.NET\PCRE.NET.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" NoWarn="NU1608" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="PublicApiGenerator" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.NUnit" />
    <PackageReference Include="Verify.SourceGenerators" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\PCRE\testdata\test*" Link="Pcre/TestCases/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\NuGetReadme.md" CopyToOutputDirectory="PreserveNewest" Visible="false" />
    <None Include="..\..\README.md" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

</Project>
