name: Build
on: [ push, pull_request ]

env:
  BUILD_CONFIGURATION: Release
  BUILD_NET_SDK: 10.0.x
  BUILD_NET_TEST_TARGET: net10.0
  BUILD_NETFWK_TEST_TARGET: net481
  DOTNET_NOLOGO: 1
  NUGET_CERT_REVOCATION_MODE: offline
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  TERM: xterm

jobs:
  unix:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64
            runner: ubuntu-latest
            platform: x64
            extension: so

          - name: Linux arm64
            runner: ubuntu-24.04-arm
            platform: arm64
            extension: so

          - name: macOS arm64
            runner: macos-15
            platform: arm64
            extension: dylib

          - name: macOS x64
            runner: macos-15-intel
            platform: x64
            extension: dylib

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.BUILD_NET_SDK }}

      - name: CMake
        run: |
          mkdir src/cmake
          cd src/cmake
          cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_CONFIGURATION }}

      - name: Build Native
        run: |
          cd src/cmake
          make

      - name: Copy Native Lib
        run: |
          mkdir lib
          cp src/cmake/PCRE.NET.Native.${{ matrix.extension }} lib/PCRE.NET.Native.${{ matrix.platform }}.${{ matrix.extension }}

      - name: Test .NET
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests/PCRE.NET.Tests.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          -p:PcreNetTestBuild=true
          -p:ExpectPlatform=${{ matrix.platform }}

      - name: Test .NET Standard
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests/PCRE.NET.Tests.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          -p:PcreNetTestBuild=true
          -p:ExpectPlatform=${{ matrix.platform }}
          -p:ForceNetStandard=true

      - name: Test Allocations
        run: >-
          dotnet run
          --project src/PCRE.NET.Benchmarks/PCRE.NET.Benchmarks.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          --
          --allocations

      - name: Test Local Integration
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests.Integration/PCRE.NET.Tests.Integration.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}

      - name: Upload Native Lib
        uses: actions/upload-artifact@v7
        with:
          name: lib-${{ matrix.platform }}.${{ matrix.extension }}
          path: lib/PCRE.NET.Native.${{ matrix.platform }}.${{ matrix.extension }}
          if-no-files-found: error

  windows:
    name: Build Windows ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86
            runner: windows-2025-vs2026
            msbuild-platform: Win32

          - platform: x64
            runner: windows-2025-vs2026
            msbuild-platform: x64

          - platform: arm64
            runner: windows-11-vs2026-arm
            msbuild-platform: ARM64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.BUILD_NET_SDK }}
          architecture: ${{ matrix.platform }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: ${{ matrix.platform }}

      - name: NuGet Restore
        run: >-
          dotnet restore
          src/PCRE.NET.slnx
          -p:DisableWarnForInvalidRestoreProjects=true

      - name: Build Native
        run: >-
          msbuild src/PCRE.NET.Native/PCRE.NET.Native.vcxproj
          -p:Configuration=${{ env.BUILD_CONFIGURATION }}
          -p:Platform=${{ matrix.msbuild-platform }}

      - name: Test .NET
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests/PCRE.NET.Tests.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          --runtime win-${{ matrix.platform }}
          -p:PcreNetTestBuild=true
          -p:ExpectPlatform=${{ matrix.platform }}

      - name: Test .NET Standard
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests/PCRE.NET.Tests.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          --runtime win-${{ matrix.platform }}
          -p:PcreNetTestBuild=true
          -p:ExpectPlatform=${{ matrix.platform }}
          -p:ForceNetStandard=true

      - name: Test .NET Framework
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests/PCRE.NET.Tests.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NETFWK_TEST_TARGET }}
          --runtime win-${{ matrix.platform }}
          -p:PcreNetTestBuild=true
          -p:ExpectPlatform=${{ matrix.platform }}

      - name: Test Allocations .NET
        run: >-
          dotnet run
          --project src/PCRE.NET.Benchmarks/PCRE.NET.Benchmarks.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          --runtime win-${{ matrix.platform }}
          --
          --allocations

      - name: Test Allocations .NET Framework
        run: >-
          dotnet run
          --project src/PCRE.NET.Benchmarks/PCRE.NET.Benchmarks.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NETFWK_TEST_TARGET }}
          --runtime win-${{ matrix.platform }}
          --
          --allocations

      - name: Test Local Integration
        run: >-
          dotnet run
          --project src/PCRE.NET.Tests.Integration/PCRE.NET.Tests.Integration.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --framework ${{ env.BUILD_NET_TEST_TARGET }}
          --runtime win-${{ matrix.platform }}

      - name: Upload Native Lib
        uses: actions/upload-artifact@v7
        with:
          name: lib-${{ matrix.platform }}.dll
          path: lib/PCRE.NET.Native.${{ matrix.platform }}.dll
          if-no-files-found: error

  pack:
    name: Pack
    runs-on: ubuntu-latest
    needs:
      - unix
      - windows

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.BUILD_NET_SDK }}

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: lib
          merge-multiple: true

      - name: Delete Native Lib Artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: lib-*
          failOnError: false

      - name: NuGet Restore
        run: dotnet restore src/PCRE.NET/PCRE.NET.csproj

      - name: Build PCRE.NET
        run: >-
          dotnet build
          src/PCRE.NET/PCRE.NET.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --no-restore
          -p:PcreNetPackage=true

      - name: NuGet Pack
        run: >-
          dotnet pack
          src/PCRE.NET/PCRE.NET.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --no-build
          -p:PcreNetPackage=true

      - name: Upload NuGet
        uses: actions/upload-artifact@v7
        with:
          name: NuGet
          path: src/PCRE.NET/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg
          archive: false
          if-no-files-found: error

  integration-tests:
    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    needs:
      - pack

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64
            runner: ubuntu-latest
            build-args: -r linux-x64
            run-args: --net=core --rid=linux-x64 --arch=x64 --aot

          - name: Linux arm64
            runner: ubuntu-24.04-arm
            build-args: -r linux-arm64
            run-args: --net=core --rid=linux-arm64 --arch=arm64 --aot

          - name: macOS arm64
            runner: macos-15
            build-args: -r osx-arm64
            run-args: --net=core --rid=osx-arm64 --arch=arm64 --aot

          - name: macOS x64
            runner: macos-15-intel
            build-args: -r osx-x64
            run-args: --net=core --rid=osx-x64 --arch=x64 --aot

          - name: Windows x86
            runner: windows-latest
            build-args: -r win-x86
            run-args: --net=core --rid=win-x86 --arch=x86 --aot

          - name: Windows x64
            runner: windows-latest
            build-args: -r win-x64
            run-args: --net=core --rid=win-x64 --arch=x64 --aot

          - name: Windows arm64
            runner: windows-11-vs2026-arm
            build-args: -r win-arm64
            run-args: --net=core --rid=win-arm64 --arch=arm64 --aot

          - name: Windows x86, .NET Framework
            runner: windows-latest
            build-args: -p:TargetFramework=net481 -p:Prefer32Bit=true
            run-args: --net=framework --rid=win-x86 --arch=x86

          - name: Windows x64, .NET Framework
            runner: windows-latest
            build-args: -p:TargetFramework=net481 -p:Prefer32Bit=false
            run-args: --net=framework --rid=win-x64 --arch=x64

          - name: Windows arm64, .NET Framework, Native
            runner: windows-11-vs2026-arm
            build-args: -p:TargetFramework=net481 -p:Prefer32Bit=false -p:PreferNativeArm64=true
            run-args: --net=framework --rid=win-arm64 --arch=arm64

          - name: Windows arm64, .NET Framework, Emulation
            runner: windows-11-vs2026-arm
            build-args: -p:TargetFramework=net481 -p:Prefer32Bit=false -p:PreferNativeArm64=false
            run-args: --net=framework --rid=win-x64 --arch=x64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.BUILD_NET_SDK }}

      - name: Download NuGet
        uses: actions/download-artifact@v8
        with:
          pattern: PCRE.NET.*.nupkg
          path: src/PCRE.NET.Tests.Integration/nuget
          skip-decompress: true

      - name: Restore
        run: >-
          dotnet restore
          src/PCRE.NET.Tests.Integration/PCRE.NET.Tests.Integration.csproj
          -p:UsePcreNetNuGetPackage=true
          ${{ matrix.build-args }}

      - name: Build
        run: >-
          dotnet build
          src/PCRE.NET.Tests.Integration/PCRE.NET.Tests.Integration.csproj
          --no-restore
          -p:UsePcreNetNuGetPackage=true
          ${{ matrix.build-args }}

      - name: Publish
        run: >-
          dotnet publish
          src/PCRE.NET.Tests.Integration/PCRE.NET.Tests.Integration.csproj
          --no-build
          --output ./bin/publish
          -p:UsePcreNetNuGetPackage=true
          ${{ matrix.build-args }}

      - name: Run
        run: >-
          ./bin/publish/PCRE.NET.Tests.Integration
          --nuget
          ${{ matrix.run-args }}
