using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace PCRE.NET.Analyzers.Support;

internal static class GeneratorHelpers
{
    public static readonly SymbolDisplayFormat ParametersFormat
        = new(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            memberOptions: SymbolDisplayMemberOptions.IncludeParameters,
            parameterOptions: SymbolDisplayParameterOptions.IncludeName
                              | SymbolDisplayParameterOptions.IncludeType
                              | SymbolDisplayParameterOptions.IncludeModifiers,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
                                  | SymbolDisplayMiscellaneousOptions.UseSpecialTypes
                                  | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

    extension(CodeWriter writer)
    {
        private void AppendHeader()
        {
            writer.AppendLine(
                """
                // <auto-generated />

                #nullable enable

                """
            );
        }

        public void AppendInterceptorHeader()
        {
            writer.AppendHeader();

            writer.AppendLine(
                """
                namespace System.Runtime.CompilerServices
                {
                    [global::System.Diagnostics.Conditional("PCRE_GENERATED")]
                    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                    file sealed class InterceptsLocationAttribute : global::System.Attribute
                    {
                        public InterceptsLocationAttribute(int version, string data)
                        {
                        }
                    }
                }

                """
            );
        }

        public void AppendInterceptsLocationAttributeLine(InterceptableLocation location)
        {
            writer.Append(location.GetInterceptsLocationAttributeSyntax())
#if DEBUG
                  .Append(" // ").Append(location.GetDisplayLocation())
#endif
                  .AppendLine();
        }
    }
}
