#!/usr/bin/env dotnet

// To update PCRE2:
// - Delete the contents of the PCRE directory
// - Extract the PCRE2 release into the PCRE directory
// - Run this script: dotnet UpdatePcre2.cs

#:include UpdatePcre2.Data.cs
#:include ../PCRE.NET.Analyzers/Analyzers/CodeWriter.cs

using System.Net;
using System.Text.RegularExpressions;
using PCRE.Analyzers;

var rootPath = GetRepositoryRootPath();
var pcre2SrcDir = Path.Combine(rootPath, "src", "PCRE", "src");
var internalDir = Path.Combine(rootPath, "src", "PCRE.NET", "Internal");

Console.WriteLine($"Updating PCRE2 in repository: {rootPath}");

// Patch PCRE2
{
    File.Copy(
        Path.Combine(pcre2SrcDir, "pcre2.h.generic"),
        Path.Combine(pcre2SrcDir, "pcre2.h"),
        overwrite: true
    );

    File.Copy(
        Path.Combine(pcre2SrcDir, "pcre2_chartables.c.dist"),
        Path.Combine(pcre2SrcDir, "pcre2_chartables.c"),
        overwrite: true
    );

    File.WriteAllText(
        Path.Combine(pcre2SrcDir, "config.h"),
        // language=cpp
        $"""

         #include "../../PCRE.NET.Native/pcre2config.h"

         {File.ReadAllText(Path.Combine(pcre2SrcDir, "config.h.generic"))}
         """.ReplaceLineEndings("\n")
    );
}

var constants = PcreConstant.ParsePcre2Header(Path.Combine(pcre2SrcDir, "pcre2.h")).ToArray();
var writer = new CodeWriter();

// Update PcreConstants.cs
{
    writer.Clear().AppendLine(
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        namespace PCRE.Internal;

        """
    );

    using (writer.WriteBlock("internal static class PcreConstants"))
    {
        foreach (var (type, name, value) in constants)
            writer.AppendLine($"public const {type} {name} = {value};");
    }

    File.WriteAllText(
        Path.Combine(internalDir, "PcreConstants.cs"),
        writer.ToString()
    );
}

// Update PcreErrorCode.cs
{
    var errorCodeFilePath = Path.Combine(rootPath, "src", "PCRE.NET", "PcreErrorCode.cs");
    var fileContents = File.ReadAllText(errorCodeFilePath);
    var match = Regex.Match(
        fileContents,
        """
        ^[ ]*\#region[ ]+Generated\r?\n
        (?<generated>.*?)
        ^[ ]*\#endregion\r?\n
        """,
        RegexOptions.CultureInvariant | RegexOptions.IgnorePatternWhitespace | RegexOptions.Singleline | RegexOptions.Multiline
    );

    if (!match.Success)
        throw new InvalidOperationException("Could not find the generated region in PcreErrorCode.cs.");

    var generatedGroup = match.Groups["generated"];
    writer.Clear().AppendLine(fileContents[..generatedGroup.Index]);

    using (writer.Indented())
    {
        const string errorPrefix = "PCRE2_ERROR_";

        var errorCodes = constants.Where(i => i.Name.StartsWith(errorPrefix))
                                  .Select(i => (i.Name, i.Value))
                                  .ToList();

        var errorMessages = PcreErrorMessage.ParseErrorFile(Path.Combine(pcre2SrcDir, "pcre2_error.c"))
                                            .ToDictionary(i => i.Value, i => i.Message);

        foreach (var (constantName, errorCode) in errorCodes)
        {
            var constantNameWithoutPrefix = constantName.Substring(errorPrefix.Length);
            var memberName = constantNameWithoutPrefix;

            foreach (var cut in UpdateData.CutPositions)
            {
                if (constantNameWithoutPrefix == cut.Replace("|", string.Empty))
                {
                    memberName = cut.Replace("|", "_");
                    break;
                }
            }

            memberName = Regex.Replace(memberName.ToLowerInvariant(), @"(?:^|_)(?<char>\w)", m => m.Groups["char"].Value.ToUpperInvariant());

            var errorMessage = errorMessages[int.Parse(errorCode)];

            errorMessage = WebUtility.HtmlEncode(errorMessage)
                                     .Replace("&#39;", "'");

            errorMessage = Regex.Replace(
                errorMessage,
                """
                (?<=^|[ ])
                (?:
                    [a-z0-9]+_[a-z0-9_]+ \(\)  # Function
                    | \\   [^ ]+               # Escape
                    | \(\? [^ ]+               # Group
                    | \(\* [a-zA-Z_]+ \)       # Verb
                    | { [^}]+ }                # Braces
                    | (?! POSIX | ASCII | UTF | UCP | DFA | JIT) [A-Z]{2,}
                    | (?! - ) \W+
                    | ^erroroffset
                )
                (?=[ :),]|$)
                """,
                "<c>$0</c>",
                RegexOptions.CultureInvariant | RegexOptions.IgnorePatternWhitespace
            );

            errorMessage = errorMessage.Replace(",</c>", "</c>,");

            if (char.IsLower(errorMessage[0]))
                errorMessage = char.ToUpperInvariant(errorMessage[0]) + errorMessage.Substring(1);

            var lastChar = errorMessage[^1];
            if ((!char.IsPunctuation(lastChar) || lastChar is ')') && (!errorMessage.EndsWith("</c>") || errorMessage.EndsWith("()</c>")))
                errorMessage += ".";

            writer.AppendLine("/// <summary>");
            writer.AppendLine($"/// <c>{constantName}</c> - {errorMessage}");
            writer.AppendLine("/// </summary>");
            writer.AppendLine($"{memberName} = PcreConstants.{constantName},");
            writer.AppendLine();
        }
    }

    writer.AppendLine().Append(fileContents[(generatedGroup.Index + generatedGroup.Length)..]);
    File.WriteAllText(errorCodeFilePath, writer.ToString());
    // Console.WriteLine(writer.ToString());
}

Console.WriteLine("PCRE2 release patched successfully.");
return;

static string GetRepositoryRootPath()
{
    for (var path = Environment.CurrentDirectory; path is not null; path = Path.GetDirectoryName(path))
    {
        if (Directory.Exists(Path.Combine(path, ".git")))
            return path;
    }

    throw new InvalidOperationException("Could not find the repository root path.");
}
