#!/usr/bin/env dotnet

// To update PCRE2:
// - Delete the contents of the PCRE directory
// - Extract the PCRE2 release into the PCRE directory
// - Run this script: dotnet run UpdatePcre2.cs

#:include ../PCRE.NET.Analyzers/Analyzers/CodeWriter.cs

using System.Text.RegularExpressions;
using PCRE.Analyzers;

var rootPath = GetRepositoryRootPath();
var pcre2SrcDir = Path.Combine(rootPath, "src", "PCRE", "src");
var internalDir = Path.Combine(rootPath, "src", "PCRE.NET", "Internal");

Console.WriteLine($"Updating PCRE2 in repository: {rootPath}");

// Patch PCRE2
{
    File.Copy(
        Path.Combine(pcre2SrcDir, "pcre2.h.generic"),
        Path.Combine(pcre2SrcDir, "pcre2.h"),
        overwrite: true
    );

    File.Copy(
        Path.Combine(pcre2SrcDir, "pcre2_chartables.c.dist"),
        Path.Combine(pcre2SrcDir, "pcre2_chartables.c"),
        overwrite: true
    );

    File.WriteAllText(
        Path.Combine(pcre2SrcDir, "config.h"),
        // language=cpp
        $"""

         #include "../../PCRE.NET.Native/pcre2config.h"

         {File.ReadAllText(Path.Combine(pcre2SrcDir, "config.h.generic"))}
         """.ReplaceLineEndings("\n")
    );
}

// language=cs
const string commonHeader = """
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    // </auto-generated>
    //------------------------------------------------------------------------------

    #nullable enable

    namespace PCRE.Internal;

    """;

// Update PcreConstants.cs
{
    var commentRe = new Regex(
        @"/\* .*? \*/",
        RegexOptions.CultureInvariant | RegexOptions.IgnorePatternWhitespace
    );

    var defineRe = new Regex(
        """
        ^ \s* \# \s* define \s+
        (?<name>PCRE2_\w+) \s+
        \(? \s*
        (?<value> -? (?:0x)? [0-9]+ )
        [uU]?
        \s* \)?
        \s* $
        """,
        RegexOptions.CultureInvariant | RegexOptions.IgnorePatternWhitespace | RegexOptions.Multiline
    );

    var toIgnore = new HashSet<string>
    {
        "PCRE2_MAJOR",
        "PCRE2_MINOR",
        "PCRE2_LOCAL_WIDTH"
    };

    var constants = new List<(string type, string name, string value)>();

    foreach (var fileLine in File.ReadLines(Path.Combine(pcre2SrcDir, "pcre2.h")))
    {
        if (fileLine.IndexOf("Obsolete", StringComparison.OrdinalIgnoreCase) >= 0)
            continue;

        var line = commentRe.Replace(fileLine, string.Empty);
        var m = defineRe.Match(line);

        if (!m.Success)
            continue;

        var (name, value) = (m.Groups["name"].Value, m.Groups["value"].Value);

        if (toIgnore.Contains(name))
            continue;

        var type = name.StartsWith("PCRE2_ERROR_") ? "int" : "uint";

        constants.Add((type, name, value));
    }

    var writer = new CodeWriter();
    writer.AppendLine(commonHeader);

    using (writer.WriteBlock("internal static class PcreConstants"))
    {
        foreach (var (type, name, value) in constants)
            writer.AppendLine($"public const {type} {name} = {value};");
    }

    File.WriteAllText(
        Path.Combine(internalDir, "PcreConstants.cs"),
        writer.ToString()
    );
}

Console.WriteLine("PCRE2 release patched successfully.");
return;

static string GetRepositoryRootPath()
{
    for (var path = Environment.CurrentDirectory; path is not null; path = Path.GetDirectoryName(path))
    {
        if (Directory.Exists(Path.Combine(path, ".git")))
            return path;
    }

    throw new InvalidOperationException("Could not find the repository root path.");
}
