#!/usr/bin/env dotnet

// To update PCRE2:
// - Delete the contents of the PCRE directory
// - Extract the PCRE2 release into the PCRE directory
// - Run this script: dotnet UpdatePcre2.cs

#:include UpdatePcre2.Data.cs
#:include ../PCRE.NET.Analyzers/Analyzers/CodeWriter.cs

using System.Text.RegularExpressions;
using PCRE.Analyzers;

var rootPath = GetRepositoryRootPath();
var pcre2SrcDir = Path.Combine(rootPath, "src", "PCRE", "src");
string pcre2Version;

Console.WriteLine();
Console.WriteLine($"Updating PCRE2 in repository: {rootPath}");

var constants = PcreConstant.Parse(
    Path.Combine(pcre2SrcDir, "pcre2.h.generic"),
    Path.Combine(rootPath, "src", "PCRE.NET", "PcreOptions.cs"),
    Path.Combine(rootPath, "src", "PCRE.NET", "PcreExtraCompileOptions.cs")
).ToArray();

var writer = new CodeWriter();

PatchPcre2();
UpdatePcreConstants();
UpdatePcreErrorCode();

Console.WriteLine();
Console.WriteLine($"PCRE2 successfully updated to version {pcre2Version}");
return;

static string GetRepositoryRootPath()
{
    for (var path = Environment.CurrentDirectory; path is not null; path = Path.GetDirectoryName(path))
    {
        if (Directory.Exists(Path.Combine(path, ".git")))
            return path;
    }

    throw new InvalidOperationException("Could not find the repository root path.");
}

void PatchPcre2()
{
    (string fileName, string[] includes)[] patches =
    [
        ("pcre2.h", ["pcre2.h.generic"]),
        ("pcre2_chartables.c", ["pcre2_chartables.c.dist"]),
        ("config.h", ["../../PCRE.NET.Native/pcre2config.h", "config.h.generic"])
    ];

    foreach (var (fileName, filesToInclude) in patches)
    {
        var identifier = $"PCRENET_{fileName.Replace('.', '_').ToUpperInvariant()}";
        var isHeaderFile = fileName.EndsWith(".h", StringComparison.Ordinal);

        writer.Clear()
              .AppendLine()
              .AppendLine("/* Generated with UpdatePcre2.cs */")
              .AppendLine();

        if (isHeaderFile)
        {
            writer.AppendLine($"#ifndef {identifier}")
                  .AppendLine($"#define {identifier}")
                  .AppendLine();
        }

        foreach (var fileToInclude in filesToInclude)
        {
            writer.AppendLine($"""
                #include "{fileToInclude}"
                """
            );
        }

        if (isHeaderFile)
        {
            writer.AppendLine()
                  .AppendLine($"#endif /* {identifier} */");
        }

        File.WriteAllText(
            Path.Combine(pcre2SrcDir, fileName),
            writer.ToString().ReplaceLineEndings("\n")
        );
    }

    var configFile = File.ReadAllText(Path.Combine(pcre2SrcDir, "config.h.generic"));

    pcre2Version = Regex.Match(
        configFile,
        """
        ^\s*#define\s+PACKAGE_VERSION\s+"(?<version>[\w.-]+)"
        """,
        RegexOptions.CultureInvariant | RegexOptions.Multiline
    ).Groups["version"].Value;

    Console.WriteLine(" ✅ PCRE2 patched");
}

void UpdatePcreConstants()
{
    writer.Clear().AppendLine(
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by UpdatePcre2.cs - do not update manually.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        namespace PCRE.Internal;

        """
    );

    using (writer.WriteBlock("internal static class PcreConstants"))
    {
        foreach (var (type, name, value, _) in constants)
            writer.AppendLine($"public const {type} {name} = {value};");
    }

    File.WriteAllText(
        Path.Combine(rootPath, "src", "PCRE.NET", "Internal", "PcreConstants.cs"),
        writer.ToString()
    );

    Console.WriteLine(" ✅ PcreConstants.cs updated");
}

void UpdatePcreErrorCode()
{
    var errorCodeFilePath = Path.Combine(rootPath, "src", "PCRE.NET", "PcreErrorCode.cs");
    var fileContents = File.ReadAllText(errorCodeFilePath);
    var match = Regex.Match(
        fileContents,
        """
        ^[ ]*\#region[ ]+Generated\r?\n
        (?<generated>.*?)
        ^[ ]*\#endregion\r?\n
        """,
        RegexOptions.CultureInvariant | RegexOptions.IgnorePatternWhitespace | RegexOptions.Singleline | RegexOptions.Multiline
    );

    if (!match.Success)
        throw new InvalidOperationException("Could not find the generated region in PcreErrorCode.cs.");

    var generatedGroup = match.Groups["generated"];
    writer.Clear().AppendLine(fileContents[..generatedGroup.Index]);

    using (writer.Indented())
    {
        var errorMessages = PcreErrorMessage.ParseErrorFile(Path.Combine(pcre2SrcDir, "pcre2_error.c"))
                                            .ToDictionary(i => i.Value);

        var constantMapping = constants.Where(i => i.OptionFullName is not null)
                                       .ToDictionary(i => i.Name, i => i.OptionFullName);

        foreach (var constant in constants.Where(i => i.IsError))
        {
            var errorMessage = errorMessages[int.Parse(constant.Value)].ToXmlDocComment();

            errorMessage = Regex.Replace(
                errorMessage,
                @"\bPCRE2_[A-Z0-9_]+",
                m => constantMapping.TryGetValue(m.Value, out var optionFullName)
                    ? $"<see cref=\"{optionFullName}\"/>"
                    : $"<c>{m.Value}</c>"
            );

            errorMessage = errorMessage.Replace("INT_MAX", "<see cref=\"int.MaxValue\"/>");

            writer.AppendLine("/// <summary>");
            writer.AppendLine($"/// <c>{constant.Name}</c> - {errorMessage}");
            writer.AppendLine("/// </summary>");
            writer.AppendLine($"{constant.ToMemberName()} = PcreConstants.{constant.Name},");
            writer.AppendLine();
        }
    }

    writer.AppendLine().Append(fileContents[(generatedGroup.Index + generatedGroup.Length)..]);
    File.WriteAllText(errorCodeFilePath, writer.ToString());

    Console.WriteLine(" ✅ PcreErrorCode.cs updated");
}
